version: "3"
services:
  web:
    image: index.docker.io/datalync/test:latest
    ports:
      - "5000:5000"
  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    hostname: watchtower
    restart: unless-stopped
    command: --schedule "0 0 0 * * *"
    environment:
      - TZ=Australia/Brisbane
      - WATCHTOWER_CLEANUP=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
